baseURL = "https://bootlicker.party/"
languageCode = "en-au"
title = "BOOTLICKER"
theme = "elephants"

[params]
    sitename = "BOOTLICKER"
    DateForm = "2006-01-02"
    
[permalinks]
  post = "/:year/:month/:day/:title/"

  

