baseURL = "https://bootlicker.party/"
languageCode = "en-au"
title = "BOOTLICKER"
theme = "elephants"

[params]
    sitename = "BOOTLICKER"
    
[permalinks]
  post = "/:year/:month/:day/:title/"
  

